AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # IAM Settings
  LambdaCustomPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: Lambda-Policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action:
              - s3:ListAllMyBuckets
              - s3:ListBucket
              - s3:GetObject
            # [TODO] Resourceの修正
            Resource: "*"
          -
            Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            # [TODO] Resourceの修正
            Resource: "*"
          -
            Effect: Allow
            Action:
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ReceiveMessage
              - sqs:sendMessage
            # [TODO] Resourceの修正
            Resource: "*"
          -
            Effect: Allow
            Action:
              - dynamodb:Get*
              - dynamodb:Query
              - dynamodb:PutItem
              - dynamodb:Delete
            # [TODO] Resourceの修正
            Resource: "*"
  InlinePolicy:
     Type: 'AWS::IAM::Policy'
     Properties:
        PolicyName: Lambda-Runcommand-InlinePolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - 
              Effect: Allow
              Action:
                - ssm:SendCommand
                - ssm:ListCommandInvocations
                - ssm:GetCommandInvocation
              # [TODO] Resourceの修正
              Resource: '*'
        Roles:
          - !Ref SecondLambdaRole
  
  FirstLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref LambdaCustomPolicy

  SecondLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref LambdaCustomPolicy

  # FirstSQS Settings
  FirstSQSDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: dev-lambda1-dead-letter-queue
  FirstSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 60
      QueueName: dev-lambda1-letter-queue
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt: 
            - "FirstSQSDeadLetterQueue"
            - "Arn"
        # メッセージが配信不能キューに移動される前にソースキューに配信された回数。
        maxReceiveCount: 1
      # メッセージがキューから配信された後、メッセージが使用できなくなる時間の長さ。
      VisibilityTimeout: 10

  # SecondSQS Settings
  SecondSQSDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: dev-lambda2-dead-letter-queue
  SecondSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 60
      QueueName: dev-lambda2-letter-queue
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt: 
            - "SecondSQSDeadLetterQueue"
            - "Arn"
        # メッセージが配信不能キューに移動される前にソースキューに配信された回数。
        maxReceiveCount: 1
      # メッセージがキューから配信された後、メッセージが使用できなくなる時間の長さ。
      VisibilityTimeout: 10
  # DynamoDB Settings
  Lambda1toDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "N"
        -
          AttributeName: "user_name"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
        -
          AttributeName: "user_name"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "Lambda1-DynamoDBTable"

Outputs: 
  FirstSQSQueueURL: 
    Description: "URL of new First SQS Queue"
    Value: 
      Ref: FirstSQSQueue
  FirstSQSDeadLetterQueueURL: 
    Description: "URL of new FirstSQS DeadLetterQueue"
    Value: 
      Ref: FirstSQSDeadLetterQueue
  FirstSQSQueueURL: 
    Description: "ARN of new FirstSQS Queue"
    Value: 
          Fn::GetAtt: 
            - "FirstSQSQueue"
            - "Arn"
  FirstSQSDeadLetterQueueARN: 
    Description: "ARN of new FirstSQS DeadLetterQueue"
    Value: 
          Fn::GetAtt: 
            - "FirstSQSDeadLetterQueue"
            - "Arn"

  SecondSQSQueueURL: 
    Description: "URL of new SecondSQS Queue"
    Value: 
      Ref: SecondSQSQueue
  SecondSQSDeadLetterQueueURL: 
    Description: "URL of new SecondSQS DeadLetterQueue"
    Value: 
      Ref: SecondSQSDeadLetterQueue
  SecondSQSQueueURL: 
    Description: "ARN of new SecondSQS Queue"
    Value: 
          Fn::GetAtt: 
            - "SecondSQSQueue"
            - "Arn"
  SecondSQSDeadLetterQueueARN: 
    Description: "ARN of new SecondSQS DeadLetterQueue"
    Value: 
          Fn::GetAtt: 
            - "SecondSQSDeadLetterQueue"
            - "Arn"
  # DynamoDBのTableName出力
  DynameDBName: 
    Description: "Name of DynamoDB TableName"
    Value: 
    Value: 
      Ref: Lambda1toDynamoDBTable

